version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: /scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: /scripts/stop_server
      timeout: 300
      runas: ec2-user
  Deploy:
    - location: /scripts/deploy.sh
      timeout: 900
      runas: ec2-user
    
