version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www/myapp
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: webuser
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: webuser
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 60
      runas: root
