version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - pip install --upgrade awscli
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 650691777252.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker build -t agresive . 

  post_build:
    commands:
      - echo Build completed on $(date)
      - docker images
      - echo Pushing the Docker image...
      - docker tag agresive-main:latest 650691777252.dkr.ecr.us-east-1.amazonaws.com/agresive:latest
      - docker push 650691777252.dkr.ecr.us-east-1.amazonaws.com/agresive:latest

artifacts:
  files:
    - '**/*'
  name: build-artifact-name
  discard-paths: no
