export const ApplicationConstant ={
    SIGNUP_URL_PATH:"/signup",
    SIGNIN_URL_PATH:"/signin",
    FORGOT_PASSWORD_URL_PATH:"/forgot-password",

    DASHBOARD_URL_PATH:'/dashboard',
    PRODUCTS_URL_PATH:'/products',
    ORDERS_URL_PATH:'/orders',
    QUOTATIONS_URL_PATH:'/quotations',
    REQUEST_URL_PATH:'/requests',
    CERTIFICATIONS_URL_PATH:'/certifications',
    FINANCE_URL_PATH:'/finance',
    QGRADE_URL_PATH:'/qgrade',
    ADVISORY_URL_PATH:'/advisory',
    INSURANCE_URL_PATH:'/insurance',
    INSPECTION_URL_PATH:'/inspection',
    CART_URL_PATH:'/cart',
    ADDPRODUCT_URL_PATH:"/addproduct",
    NEWQUOTATION_URL_PATH:"/newquotation",
    ADVISORYREQUEST_URL_PATH:"/advisoryRequest",
    FINANCEREQUEST_URL_PATH:"/financeRequest",
    QGRADEREQUEST_URL_PATH:"/qgradeRequest",
    CERTIFICATIONREQUEST_URL_PATH:"/certificationRequest",
    SUCCESS_MSG:"Successfully Submitted. Req Id: ",
    SUCCESS_UPD_MSG:"Successfully Updated."
}