name: Continuous Integration

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  pull_request:
    branches:
      - newbase  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Adjust this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npm run build  # Replace with your build command

#       - name: Run tests
#         run: npm test  # Replace with your test command
