name: Build

on:
  push:
    branches:
      - newbase
jobs:
  build-and-deploy:
    runs-on: Amazon Linux (inferred)
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: newbase

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build
